//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapShopv2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LapShopv2.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name .
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu.
        /// </summary>
        public static string lblGpu {
            get {
                return ResourceManager.GetString("lblGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardDisk.
        /// </summary>
        public static string lblHardDisk {
            get {
                return ResourceManager.GetString("lblHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item Name .
        /// </summary>
        public static string LblItemName {
            get {
                return ResourceManager.GetString("LblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string LblItemType {
            get {
                return ResourceManager.GetString("LblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string LblOs {
            get {
                return ResourceManager.GetString("LblOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LblPrice {
            get {
                return ResourceManager.GetString("LblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string LblProcessor {
            get {
                return ResourceManager.GetString("LblProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string LblPurchasePrice {
            get {
                return ResourceManager.GetString("LblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram Size.
        /// </summary>
        public static string lblRamSize {
            get {
                return ResourceManager.GetString("lblRamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price .
        /// </summary>
        public static string LblSalesPrice {
            get {
                return ResourceManager.GetString("LblSalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reslution.
        /// </summary>
        public static string lblScreenReslution {
            get {
                return ResourceManager.GetString("lblScreenReslution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string lblScreenSize {
            get {
                return ResourceManager.GetString("lblScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Home Page.
        /// </summary>
        public static string LblShowHomePage {
            get {
                return ResourceManager.GetString("LblShowHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string LblWeight {
            get {
                return ResourceManager.GetString("LblWeight", resourceCulture);
            }
        }
    }
}
